config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
  controllers: { passwords: 'users/passwords',
                 registrations: 'users/registrations' ,
                 sessions: 'users/sessions'
                }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "items#index"
  resources :signup, only: [:index, :create] do
    collection do
      get "step1"
      get "step2"
      get "step3"
      get "step4"
      get "step5" 
      get "step6"  
    end
  end

  resources :items, only: [:index, :new, :create, :show]

  resources :mypage, only: [:index] do
    collection do
      get "logout"
    end
  end
end

app/views/shared/_aside.html.haml
.aside
  = image_tag 'top/top_aside1.png', size: "1440x260", alt: 'Mercari', class: 'img_aside-back'
  -# = image_tag 'top/top_aside_app.png', size: "144x40", alt: 'app', class: 'img_aside-app'
  -# = image_tag 'top/top_aside_google.png', size: "144x40", alt: 'google', class: 'img_aside-google'

app/views/shared/_footer.html.haml
.footer
  %nav.menu
    .menu1
      %h2.menu1__title メルカリについて
      %ul.menu1__contents
        %li.menu1__contents
          =link_to "#", class:"menu1__contents__name" do
            会社概要（運送会社）
        %li.menu1__contents
          =link_to "#", class:"menu1__contents__name" do
            採用情報
        %li.menu1__contents
          =link_to "#", class:"menu1__contents__name" do
            プレスリリース
        %li.menu1__contents
          =link_to "#", class:"menu1__contents__name" do
            公式ブログ
        %li.menu1__contents
          =link_to "#", class:"menu1__contents__name" do
            メルカリロゴ利用ガイドライン
        %li.menu1__contents__logo1
          =link_to "https://twitter.com/", class:"menu1__contents__logo1__btn--twitter" do
            %i.fab.fa-twitter
        %li.menu1__contents__logo2
          =link_to "https://www.facebook.com/", class:"menu1__contents__logo2__btn--facebook" do
            %i.fab.fa-facebook-square

    .menu2
      %h2.menu2__title ヘルプ&ガイド
      %ul.menu2__contents
        %li.menu2__contents
          =link_to "#", class:"menu2__contents__name" do
            メルカリガイド
        %li.menu2__contents
          =link_to "#", class:"menu2__contents__name" do
            らくらくメルカリ便
        %li.menu2__contents
          =link_to "#", class:"menu2__contents__name" do
            ゆうゆうメルカリ便
        %li.menu2__contents
          =link_to "#", class:"menu2__contents__name" do
            大型メルカリ便
        %li.menu2__contents
          =link_to "#", class:"menu2__contents__name" do
            車体取引メルカリ便
        %li.menu2__contents
          =link_to "#", class:"menu2__contents__name" do
            メルカリあんしん・あんぜん宣言！
        %li.menu2__contents
          =link_to "#", class:"menu2__contents__name" do
            偽ブランド品撲滅への取り組み
        %li.menu2__contents
          =link_to "#", class:"menu2__contents__name" do
            メルカリボックス


    .menu3
      %h2.menu3__title プライバシーと利用規約
      .menu3__contents
        %ul.menu3__contents__1
          %li.menu3__contents
            =link_to "#", class:"menu3__contents__1__name" do
              プライバシーポリシー
          %li.menu3__contents
            =link_to "#", class:"menu3__contents__1__name" do
              メルカリ利用規約
          %li.menu3__contents
            =link_to "#", class:"menu3__contents__1__name" do
              あんしんスマホサポート制度に関する利用規約
          %li.menu3__contents
            =link_to "#", class:"menu3__contents__1__name" do
              コンプライアンスポリシー
        %ul.menu3__contents__2
          %li.menu3__contents
            =link_to "#", class:"menu3__contents__2__name" do
              個人データの安全管理に係るる基本方針
          %li.menu3__contents
            =link_to "#", class:"menu3__contents__2__name" do
              特定商取引に関する表記
          %li.menu3__contents
            =link_to "#", class:"menu3__contents__2__name" do
              資金決済法に基づく表示
          %li.menu3__contents
            =link_to "#", class:"menu3__contents__2__name" do
              法令遵守と犯罪抑止のために

    .menu4
      %h2.menu4__title 国
      %ul.menu4__contents
        %li.menu4__contents
          =link_to "#", class:"menu4__contents__name" do
            日本
        %li.menu4__contents
          =link_to "#", class:"menu4__contents__name" do
            United States

  .buttom
    .buttom__contents
      =link_to root_path, class:"buttom__contents__btn" do
        %img{ class:"buttom__contents__btn", alt:"mercarilogo", src:"//www-mercari-jp.akamaized.net/assets/img/common/common/logo-white.svg?2482339763" }
      %span.buttom__contents__name © Mercari, inc.

app/views/shared/_header.html.haml
.header
  .header__main
    .header__main__top
      .header__main__top__logo
        =link_to root_path, class: 'header__main__top__logo__a' do
          = image_tag 'common/images-mercari.png', size: "134x36", alt: 'Mercari', class: 'header__main__top__logo__img'
      .header__main__top__search
        %form.header__main__top__search__box
          %input.header__main__top__search__box__in{placeholder: "何かお探しですか？"}
          %button.header__main__top__search__box__icon{title: '検索', type: 'submit'}
            %i.fas.fa-search

    .header__main__bottom
      .header__main__bottom__nav
        .header___main__bottom__nav__category
          =link_to '#', id: 'category-list-box' do
            %i.fas.fa-list-ul.header__main__bottom__nav__category__icon
              .header__main__bottom__nav__category__icon__text
                カテゴリーから探す

        .header__main__bottom__nav__brand
          =link_to '#', id: 'brand-list-box'do
            %i.fas.fa-tags.header__main__bottom__nav__brand__icon
              .header__main__bottom__nav__brand__icon__text
                ブランドから探す
      
      - if user_signed_in?
        .header__main__bottom__login-user
        
          =link_to '#', class: 'header__main__bottom__login-user__like-box' do
            .header__main__bottom__login-user__like-box__like-list
              いいね！一覧
            %i.far.fa-heart.header__main__bottom__login-user__like-box__icon

          =link_to '#', class: 'header__main__bottom__login-user__info-box' do
            .header__main__bottom__login-user__info-box__text
              お知らせ
            %i.far.fa-bell.header__main__bottom__login-user__info-box__icon    
    
          =link_to '#', class: 'header__main__bottom__login-user__check-box' do
            .header__main__bottom__login-user__check-box__text
              やることリスト
            %i.fas.fa-check.header__main__bottom__login-user__check-box__icon

          =link_to '#', class: 'header__main__bottom__login-user__mypage-box' do
            .header__main__bottom__login-user__mypage-box__text
              マイページ
            %i.fas.fa-user-secret.header__main__bottom__login-user__mypage-box__icon
        
      - else
        .header__main__bottom__user
          .header__main__bottom__user__register-button
            =link_to step1_signup_index_path, class:"header__main__bottom__user__register-button__text" do
              新規会員登録
          .header__bottom__user__login-button
            =link_to '#',  class:"header__main__bottom__user__login-button__text" do
              ログイン

app/views/shared/_mainpage_middle.html.haml
.toppage-main
  = image_tag 'top/top_slide1.png', size: "1440x390", alt: 'slide1', class: 'img_slide'
  .toppage-main__category-top
    人気のカテゴリー
    %ul.toppage-main__list
      %li.toppage-main__menu
        .toppage-main__logo
          レディース
        .toppage-main__logo
          メンズ
        .toppage-main__logo
          家電・スマホ・カメラ
        .toppage-main__logo
          おもちゃ・ホビー・グッズ
  .toppage-main__category-bottom
    .toppage-main__category-name
      .toppage-main__text
        レディース新着アイテム
        .toppage-main__item-more
          = link_to 'もっと見る >', '#', class: 'toppage-main__more-link'
      .toppage-main__item
        .toppage-main__contents
          - @items.each do |item|
            .toppage-main__content
              = link_to item_path(item.id) do
                .toppage-main__image
                  %span
                    -# = item.jpy
                  = image_tag item.images[0], size: '188x188'
                  -# -if item.condition_id == 4
                  -#   .pickup-content__red
                  -#   .pickup-content__sold
                  -#     SOLD
                  -# -if item.condition_id == 3
                  -#   .pickup-content__gray
                  -#   .pickup-content__stop
                  -#     公開停止
                .toppage-main__item-name
                  %span= item.name
    .toppage-main__category-name
      .toppage-main__text
        メンズ新着アイテム
        .toppage-main__item-more
          = link_to 'もっと見る >', '#', class: 'toppage-main__more-link'
      .toppage-main__item
        .toppage-main__contents
          - @items.each do |item|
            .toppage-main__content
              = link_to item_path(item.id) do
                .toppage-main__image
                  %span
                    -# = item.jpy
                  = image_tag item.images[0], resize: '188x188'
                  -# -if item.condition_id == 4
                  -#   .pickup-content__red
                  -#   .pickup-content__sold
                  -#     SOLD
                  -# -if item.condition_id == 3
                  -#   .pickup-content__gray
                  -#   .pickup-content__stop
                  -#     公開停止
                .toppage-main__item-name
                  %span= item.name
    .toppage-main__category-name
      .toppage-main__text
        家電・スマホ・カメラ新着アイテム
        .toppage-main__item-more
          = link_to 'もっと見る >', '#', class: 'toppage-main__more-link'
      .toppage-main__item
        .toppage-main__contents
          - @items.each do |item|
            .toppage-main__content
              = link_to item_path(item.id) do
                .toppage-main__image
                  %span
                    -# = item.jpy
                  = image_tag item.images[0], resize: '188x188'
                  -# -if item.condition_id == 4
                  -#   .pickup-content__red
                  -#   .pickup-content__sold
                  -#     SOLD
                  -# -if item.condition_id == 3
                  -#   .pickup-content__gray
                  -#   .pickup-content__stop
                  -#     公開停止
                .toppage-main__item-name
                  %span= item.name
    .toppage-main__category-name
      .toppage-main__text
        おもちゃ・ホビー・グッズ新着アイテム
        .toppage-main__item-more
          = link_to 'もっと見る >', '#', class: 'toppage-main__more-link'
      .toppage-main__item
        .toppage-main__contents
          - @items.each do |item|
            .toppage-main__content
              = link_to item_path(item.id) do
                .toppage-main__image
                  %span
                    -# = item.jpy
                  = image_tag item.images[0], resize: '188x188'
                  -# -if item.status_id == 4
                  -#   .pickup-content__red
                  -#   .pickup-content__sold
                  -#     SOLD
                  -# -if item.status_id == 3
                  -#   .pickup-content__gray
                  -#   .pickup-content__stop
                  -#     公開停止
                .toppage-main__item-name
                  %span= item.name
              
  =link_to new_item_path, class: 'exhibit_btn' do
    .exhibit_btn__moji
      出品
    %i.fas.fa-camera

app/views/shared/login.html.haml
.cashpage
  =render "signup/header"



  =render "signup/footer"