config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
  controllers: { passwords: 'users/passwords',
                 registrations: 'users/registrations' ,
                 sessions: 'users/sessions'
                }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "items#index"
  resources :signup, only: [:index, :create] do
    collection do
      get "step1"
      get "step2"
      get "step3"
      get "step4"
      get "step5" 
      get "step6"  
    end
  end

  resources :items, only: [:index, :new, :create, :show]

  resources :mypage, only: [:index] do
    collection do
      get "logout"
    end
  end
end

app/controllers/mypage_controller.rb
class MypageController < ApplicationController
  def index
  end

  def logout
  end
end

app/helpers/mypage_helper.rb
module MypageHelper
end

app/views/mypage/_sidebar.html.haml
.side-bar
  %nav.mypage-nav
    %ul.mypage-nav__list
      %li
        %a{href: '#', class: 'mypage-nav__list__item active'} 
          マイページ
          %i.fas.fa-chevron-right
      %li
        %a{href: '#', class: 'mypage-nav__list__item'}
          お知らせ
          %i.fas.fa-chevron-right
      %li
        %a{href: '#', class: 'mypage-nav__list__item'}
          やることリスト
          %i.fas.fa-chevron-right
      %li
        %a{href: '#', class: 'mypage-nav__list__item'}
          いいね！一覧
          %i.fas.fa-chevron-right
      %li
        %a{href: '#', class: 'mypage-nav__list__item'}
          出品する
          %i.fas.fa-chevron-right
      %li
        %a{href: '#', class: 'mypage-nav__list__item'} 
          出品した商品 - 出品中
          %i.fas.fa-chevron-right
      %li
        %a{href: '#', class: 'mypage-nav__list__item'}
          出品した商品 - 取引中
          %i.fas.fa-chevron-right
      %li
        %a{href: '#', class: 'mypage-nav__list__item'}
          出品した商品 - 売却済み
          %i.fas.fa-chevron-right
      %li
        %a{href: '#' , class: 'mypage-nav__list__item'}
          購入した商品 - 取引中
          %i.fas.fa-chevron-right
      %li
        %a{href: '#', class: 'mypage-nav__list__item'}
          購入した商品 - 過去の取引
          %i.fas.fa-chevron-right
      %li
        %a{href: '#', class: 'mypage-nav__list__item'}
          ニュース一覧
          %i.fas.fa-chevron-right
      %li
        %a{href: '#', class: 'mypage-nav__list__item'}
          評価一覧
          %i.fas.fa-chevron-right
      %li
        %a{href: '#', class: 'mypage-nav__list__item'}
          ガイド
          %i.fas.fa-chevron-right
      %li
        %a{href: '#', class: 'mypage-nav__list__item'}
          お問い合わせ
          %i.fas.fa-chevron-right

    %h3.mypage-nav__head メルペイ
    %ul.mypage-nav__list
      %li
        %a{href: '#', class: 'mypage-nav__list__item'}
          売上・振込申請
          %i.fas.fa-chevron-right
      %li
        %a{href: '#', class: 'mypage-nav__list__item'} 
          ポイント
          %i.fas.fa-chevron-right
    
    %h3.mypage-nav__head 設定
    %ul.mypage-nav__list
      %li
        %a{href: '#', class: 'mypage-nav__list__item'} 
          プロフィール
          %i.fas.fa-chevron-right
      %li
        %a{href: '#', class: 'mypage-nav__list__item'} 
          発送元・お届け先住所変更
          %i.fas.fa-chevron-right
      %li
        %a{href: "#", class: 'mypage-nav__list__item'} 
          支払い方法
          %i.fas.fa-chevron-right
      %li
        %a{href: '#', class: 'mypage-nav__list__item'} 
          メール/パスワード
          %i.fas.fa-chevron-right
      %li
        %a{href: '#', class: 'mypage-nav__list__item'} 
          本人情報
          %i.fas.fa-chevron-right
      %li
        %a{href: '#', class: 'mypage-nav__list__item'} 
          電話番号の確認
          %i.fas.fa-chevron-right
      %li
        =link_to logout_mypage_index_path, method: :get, class: 'mypage-nav__list__item' do
          ログアウト
        -# %a{href: tests_logout_path, class: 'mypage-nav__list__item'}
        -#   ログアウト
        -#   %i.fas.fa-chevron-right

app/views/mypage/index.html.haml
=render 'shared/header'
.bread_crumbs
  .bread_crumbs__line
    -# -# config/breadcrumbs.rbに定義したmypageを呼び出し
    -# - breadcrumb :mypage
    -# -# 下記を記述した箇所にパンくずリストが表示される。
    -# = breadcrumbs separator: "#{content_tag(:i, '', class: 'fas fa-chevron-right')}", class: "breadcrumbs-list"



-# - binding.pry
-# メインページ
%main.mypage_mypage.clearfix
  =render 'mypage/sidebar'
  .mypage_mypage__content
    %section.mypage_mypage__content__container
      -# ユーザーヘッド
      .mypage_mypage__content__container__user-head
        = image_tag '/user-bck_image.jpg', width: "700", height: "200", alt: "" , class: 'mypage_mypage__content__container__user-head__bck'
        .mypage_mypage__content__container__user-head__box
          .mypage_mypage__content__container__user-head__box__image
            = image_tag '/radies_sample1.jpg', width: "60", height: "60", alt: "", class: "mypage_mypage__content__container__user-head__box__image__icon"
          .mypage_mypage__content__container__user-head__box__nickname
            -# = current_user.username
          
          -# 評価と出品数
          %ul.mypage_mypage__content__container__user-head__box__numbers
            %li.mypage_mypage__content__container__user-head__box__numbers__evaluation 
              評価 20       
            %li.mypage_mypage__content__container__user-head__box__numbers__put-up 
              出品数 16

      -# お知らせ/やることリストタブ
      %ul.mypage_mypage__content__container__upper-list-tabs
        %li.mypage_mypage__content__container__upper-list-tabs__list-left--active
          %h3.mypage_mypage__content__container__upper-list-tabs__list-left__block
            =link_to "#", class: 'mypage_mypage__content__container__upper-list-tabs__list-left--active__text' do
              お知らせ
        %li.mypage_mypage__content__container__upper-list-tabs__list-right
          %h3.mypage_mypage__content__container__list-tabs__list-right__block
            =link_to "#", class: 'mypage_mypage__content__container__upper-list-tabs__list-right__text' do
              やることリスト
      -# リスト一覧
      .mypage_mypage__content__container__container-lists
        - (1..5).each do |i|
          .mypage_mypage__content__container__container-lists__list
            = image_tag 'common/fmarket_logo_red.svg', size: "", alt: "buy-item-image" , class: 'mypage_mypage__content__container__container-lists__list__image'
            .mypage_mypage__content__container__container-lists__list__text
              事務局から個別メッセージ「Goooogleログイン通知」
              %i.fas.fa-chevron-right.mypage_mypage__content__container__container-lists__list__text__icon
      
      -# 購入した商品/取引タブ
      %h2.mypage_mypage__content__container__lower-tab-head
        購入した商品
      %ul.mypage_mypage__content__container__lower-list-tabs
        %li.mypage_mypage__content__container__lower-list-tabs__list-left--active
          %h3.mypage_mypage__content__container__lower-list-tabs__list-center__block
            =link_to "#", class: 'mypage_mypage__content__container__lower-list-tabs__list-left--active__text' do
              取引中
        %li.mypage_mypage__content__container__lower-list-tabs__list-right
          %h3.mypage_mypage__content__container__lower-list-tabs__list-right__block
            =link_to "#", class: 'mypage_mypage__content__container__lower-list-tabs__list-right__text' do
              過去の取引
      -# 購入商品一覧
      .mypage_mypage__content__container__container-lists
        - (1..5).each do |i|
          .mypage_mypage__content__container__container-lists__list
            = image_tag 'common/fmarket_logo_red.svg', size: "", alt: "buy-item-image" , class: 'mypage_mypage__content__container__container-lists__list__image'
            .mypage_mypage__content__container__container-lists__list__text
              「早い者勝ち！訳あり中禅寺湖を購入しました」取引が完了しました。
              %i.fas.fa-chevron-right.mypage_mypage__content__container__container-lists__list__text__icon

      =link_to new_item_path, class: 'exhibit_btn' do
        .exhibit_btn__moji
          出品
        %i.fas.fa-camera
    -# ペイジャーは余力あったら作る
    %ul.mypage-history.pager
      %li.pager-prev.pager-cell 
        =link_to "#" do
          %i.icon-arrow-left 
      %li.pager-next.pager-cell 
        =link_to "#" do
          %i.icon-arrow-right

= render 'shared/aside'
= render 'shared/footer'

app/views/mypage/logout.html.haml
=render 'shared/header'
.logout-side-bar
  =render 'mypage/sidebar'

  .logout-contents
    .logout-contents__logout-box
      .logout-contents__logout-box__container
        .logout-contents__logout-box__container__btn-box
          = link_to destroy_user_session_path, method: :delete, class:"logout-contents__logout-box__container__btn-box__btn-red" do
            ログアウト
  
= render 'shared/aside'
= render 'shared/footer'